export type PlannerSeedPreset = {
  id: string;
  label: string;
  description: string;
  keywords: string[];
  language: string;
};

export const PLANNER_SEED_PRESETS: PlannerSeedPreset[] = [
  // ===== 일본어 (ja) =====
  {
    id: "ulthera-core",
    language: "ja",
    label: "울쎄라 핵심",
    description: "효과, 통증, 샷수, 다운타임 중심으로 Hero와 Hub 수요를 먼저 넓게 잡습니다.",
    keywords: [
      "ウルセラ",
      "ウルセラプライム",
      "ウルセラ 効果",
      "ウルセラ 痛み",
      "ウルセラ ダウンタイム",
      "ウルセラ 何ショット",
      "ウルセラ ソフウェーブ 違い",
      "ソフウェーブ",
      "ソフウェーブ 痛み",
      "ソフウェーブ ダウンタイム",
    ],
  },
  {
    id: "rejuran-core",
    language: "ja",
    label: "리쥬란 핵심",
    description: "무통, 가격, 힐러, 지속기간처럼 비교·구매 직전 의도가 강한 키워드 세트입니다.",
    keywords: [
      "リジュラン",
      "無痛リジュラン",
      "リジュラン 効果",
      "リジュラン 痛み",
      "リジュラン ダウンタイム",
      "リジュラン ヒーラー",
      "リジュラン 値段",
      "リジュラン 効果 期間",
      "無痛リジュラン 効果 期間",
      "無痛リジュラン 値段",
    ],
  },
  {
    id: "retuo-celldium",
    language: "ja",
    label: "리투오·셀디엠",
    description: "상대적으로 덜 포화된 시술군을 묶어 중간 경쟁 키워드를 한 번에 탐색합니다.",
    keywords: [
      "リトゥオ",
      "リトゥオ 効果",
      "リトゥオ 持続期間",
      "リトゥオ 目の下",
      "セルディエム",
      "セルディエム 効果",
      "セルディエム 値段",
      "セルディエム 痛み",
      "セルディエム 効果 期間",
      "セルディエム ダウンタイム",
    ],
  },
  {
    id: "geo-korea-gangnam",
    language: "ja",
    label: "한국·강남 GEO",
    description: "일본 사용자의 한국 방문 미용 탐색 의도에 맞춘 지역·병원 검색 세트입니다.",
    keywords: [
      "韓国 美容クリニック",
      "ソウル 美容クリニック",
      "ソウル 皮膚科",
      "ソウル リフトアップ",
      "韓国 皮膚科",
      "韓国 リフトアップ",
      "江南 皮膚科",
      "江南 美容クリニック",
      "江南 リジュラン",
      "江南 ウルセラ",
      "ソウル リジュラン",
      "ソウル ウルセラ",
      "韓国 リジュラン",
      "韓国 ウルセラ",
      "明洞 皮膚科",
    ],
  },
  {
    id: "onda-alltite-oligio",
    language: "ja",
    label: "온다·올타이트·올리지오",
    description: "한국 클리닉에서 자주 보이는 중고관여 리프팅 장비군을 한 번에 탐색합니다.",
    keywords: [
      "オンダリフティング",
      "オンダリフト",
      "オンダ リフティング 効果",
      "オンダ リフティング 痛み",
      "オンダ リフティング ダウンタイム",
      "オールタイト",
      "オールタイト 効果",
      "オールタイト 痛み",
      "オールタイト ダウンタイム",
      "オリジオ",
      "オリジオ 効果",
      "オリジオ 痛み",
      "オリジオ ダウンタイム",
      "オリジオ 値段",
    ],
  },
  {
    id: "volnewmer-thermage",
    language: "ja",
    label: "볼뉴머·써마지",
    description: "볼뉴머와 써마지처럼 일본 검색량은 적어도 전환가치가 큰 장비군 세트입니다.",
    keywords: [
      "ボルニューマ",
      "ボルニューマ 効果",
      "ボルニューマ 痛み",
      "ボルニューマ ダウンタイム",
      "ボルニューマ 値段",
      "サーマジ",
      "サーマクール",
      "サーマジ 効果",
      "サーマジ 痛み",
      "サーマジ ダウンタイム",
      "サーマジ 値段",
      "韓国 サーマジ",
      "江南 サーマジ",
    ],
  },
  {
    id: "hero-commercial",
    language: "ja",
    label: "Hero 상업성",
    description: "가격, 예약, 추천, 패키지처럼 상담 전환 가능성이 높은 상업 키워드만 묶었습니다.",
    keywords: [
      "ウルセラ 値段",
      "ウルセラ 予約",
      "リジュラン 値段",
      "リジュラン おすすめ",
      "韓国 美容クリニック おすすめ",
      "江南 皮膚科 おすすめ",
      "韓国 皮膚科 値段",
      "韓国 リジュラン 値段",
      "韓国 ウルセラ 値段",
      "美容クリニック パッケージ",
    ],
  },
  {
    id: "hub-hygiene",
    language: "ja",
    label: "비교·정보형",
    description: "비교, 차이, 후기, 부작용, 관리법 중심으로 Hub/Hygiene 수요를 묶었습니다.",
    keywords: [
      "ウルセラ ソフウェーブ 違い",
      "ウルセラ ダウンタイム",
      "ウルセラ 痛み",
      "リジュラン ヒーラー 違い",
      "リジュラン 副作用",
      "リジュラン ダウンタイム",
      "リジュラン 口コミ",
      "韓国 皮膚科 口コミ",
      "美容クリニック 比較",
      "韓国 美容クリニック 比較",
    ],
  },

  // ===== 한국어 (ko) — GKP 실제 검색량 기반 =====
  {
    id: "ko-ulthera-rejuran",
    language: "ko",
    label: "울쎄라·리쥬란 핵심",
    description: "울쎄라(14,800), 리쥬란(22,200) 등 한국 내 실검색량 기반 핵심 시술 키워드입니다.",
    keywords: [
      "리쥬란",
      "울쎄라",
      "울쎄라 가격",
      "울쎄라 효과",
      "리쥬란 힐러",
      "리쥬란 가격",
      "리쥬란 아이",
      "아이 리쥬란",
      "울쎄라 리프팅 가격",
      "울쎄라 후기",
      "리쥬란 주사",
      "울쎄라 유지 기간",
    ],
  },
  {
    id: "ko-lifting-devices",
    language: "ko",
    label: "리프팅 장비군",
    description: "써마지(6,600), 온다리프팅(6,600), 올리지오(3,600), 볼뉴머(2,400) 실검색량 기반입니다.",
    keywords: [
      "써마지",
      "온다 리프팅",
      "올리지오",
      "볼뉴머",
      "써마지 효과",
      "써마지 가격",
      "올리지오 효과",
      "울써마지",
      "아이 써마지",
      "써마지 전후",
      "써마지 600샷 가격",
    ],
  },
  {
    id: "ko-gangnam-clinic",
    language: "ko",
    label: "강남 피부과",
    description: "강남 피부과(1,600) 등 지역 클리닉 탐색 키워드입니다.",
    keywords: [
      "강남 피부과",
      "강남 울쎄라",
      "강남 리쥬란",
      "강남 써마지",
      "강남 피부과 추천",
      "서울 피부과",
    ],
  },
  {
    id: "ko-hero-commercial",
    language: "ko",
    label: "Hero 상업성",
    description: "가격·비용 검색 의도가 강한 고전환 키워드입니다.",
    keywords: [
      "울쎄라 가격",
      "리쥬란 가격",
      "써마지 가격",
      "필러 가격",
      "입술 필러 가격",
      "코 필러 가격",
      "팔자주름 필러 가격",
      "울쎄라 리프팅 가격",
    ],
  },

  // ===== 영어 (en) — GKP 실제 검색량 기반 =====
  {
    id: "en-ultherapy-rejuran",
    language: "en",
    label: "Ultherapy & Rejuran",
    description: "ultherapy(40,500), rejuran(27,100) 등 영어권 실검색량 기반 핵심 키워드입니다.",
    keywords: [
      "ultherapy",
      "rejuran",
      "ultherapy near me",
      "ultherapy cost",
      "thermage",
      "thermage before and after",
      "thermage near me",
      "botox korea",
    ],
  },
  {
    id: "en-skin-tightening",
    language: "en",
    label: "Skin Tightening",
    description: "skin tightening(14,800), thread lift(9,900), hifu(9,900) 실검색량 기반입니다.",
    keywords: [
      "skin tightening",
      "radio frequency skin tightening",
      "pdo threads",
      "thread lift",
      "hifu treatment",
      "hifu",
      "pdo thread lift",
      "non surgical face lift",
      "laser skin tightening",
      "skin tightening treatments",
    ],
  },
  {
    id: "en-filler-cost",
    language: "en",
    label: "Filler & Cost",
    description: "lip filler cost(18,100), under eye filler(4,400) 등 비용 검색 키워드입니다.",
    keywords: [
      "lip filler cost",
      "lip filler price",
      "lip injections cost",
      "juvederm lip filler cost",
      "under eye filler cost",
      "facetite",
      "botox korea",
    ],
  },

  // ===== 대만어 / 繁體中文 (zh-TW) — GKP 실제 검색량 기반 =====
  {
    id: "tw-rejuran-ulthera",
    language: "zh-TW",
    label: "麗珠蘭·音波拉提",
    description: "麗珠蘭(27,100), 音波拉提(6,600) 대만 실검색량 기반 핵심 키워드입니다.",
    keywords: [
      "麗珠蘭",
      "音波拉提",
      "音波拉提 費用",
      "音波拉提 效果",
      "海芙音波",
      "海芙音波 價格",
      "美國音波",
      "美國音波 價格",
      "音波拉提 dcard",
    ],
  },
  {
    id: "tw-phoenix-wave",
    language: "zh-TW",
    label: "鳳凰電波·電波拉皮",
    description: "鳳凰電波(14,800) 대만 실검색량 기반 전파 리프팅 키워드입니다.",
    keywords: [
      "鳳凰電波",
      "鳳凰電波 價格",
      "鳳凰電波 效果",
      "鳳凰電波 費用",
      "鳳凰電波 dcard",
      "電波音波",
      "碧眼電波",
      "鳳凰電波 失敗",
    ],
  },
  {
    id: "tw-korea-beauty",
    language: "zh-TW",
    label: "韓國醫美",
    description: "韓國醫美(4,400) 대만에서 한국 의료관광을 검색하는 키워드입니다.",
    keywords: [
      "韓國醫美",
      "韓國美容",
      "首爾皮膚科",
      "江南美容",
      "韓國整形",
      "韓國醫美 推薦",
    ],
  },
  {
    id: "tw-hero-commercial",
    language: "zh-TW",
    label: "Hero 費用·價格",
    description: "비용/가격 검색 의도가 강한 대만 고전환 키워드입니다.",
    keywords: [
      "音波拉提 費用",
      "鳳凰電波 價格",
      "鳳凰電波 費用",
      "海芙音波 價格",
      "海芙音波 費用",
      "音波拉提 價格 dcard",
      "鳳凰電波 價格 dcard",
      "海芙音波 600條 價格",
    ],
  },
];
